--Создание таблиц и ограничений

CREATE TABLE author (
author_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
nationality VARCHAR(50),
date_of_birth DATE NOT NULL,
date_of_death DATE
);


CREATE TABLE work (
work_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title VARCHAR(50) UNIQUE NOT NULL,
craeated_date DATE NOT NULL, 
genre_id INT,
FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);


CREATE TABLE author_work (
author_id INT,
work_id INT,
PRIMARY KEY (author_id, work_id),
FOREIGN KEY (author_id) REFERENCES author(author_id),
FOREIGN KEY (work_id) REFERENCES work(work_id)
);


CREATE TABLE genre (
genre_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE book (
book_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(50) UNIQUE NOT NULL,
publishing_house VARCHAR(50),
published_date DATE NOT NULL
);


CREATE TABLE book_work (
book_id INT,
work_id INT,
PRIMARY KEY (book_id, work_id),
FOREIGN KEY (book_id) REFERENCES book(book_id),
FOREIGN KEY (work_id) REFERENCES work(work_id)
);


CREATE TABLE order_ (
order_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
taken_date DATE NOT NULL,
return_date DATE,
book_id INT NOT NULL,
reader_id INT NOT NULL,
FOREIGN KEY (book_id) REFERENCES book(book_id),
FOREIGN KEY (reader_id) REFERENCES reader(reader_id)
);


CREATE TABLE reader (
reader_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
phone_number VARCHAR(20) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
registration_date DATE NOT NULL 
);


--Добавление новых атрибутов «sys_created_at» и «sys_changed_at» во все таблицы

ALTER TABLE author 
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE author_work 
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE book
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE book_work 
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE genre 
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE order_ 
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reader 
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE work
ADD COLUMN sys_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN sys_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;


